# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paradero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='recorrido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('mapa', models.CharField(max_length=200)),
                ('horario_inicio', models.TimeField()),
                ('horario_final', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='recorrido_paradero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.paradero')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de vehiculo',
                'verbose_name_plural': 'tipos de vehiculo',
            },
        ),
        migrations.AddField(
            model_name='linea',
            name='recorrido',
            field=models.ManyToManyField(to='principal.recorrido'),
        ),
        migrations.AddField(
            model_name='linea',
            name='tipo_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipo_vehiculo'),
        ),
    ]
