# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradero',
            old_name='google_id',
            new_name='googleid',
        ),
    ]
