# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_vehiculo',
            options={'verbose_name': 'tipo_vehiculo', 'verbose_name_plural': 'tipos de vehiculo'},
        ),
    ]
