# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20161220_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradero',
            old_name='googleid',
            new_name='google_id',
        ),
    ]
