# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20161220_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradero',
            name='google_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
