# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20161220_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='horario_final',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='horario_inicio',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='mapa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
