# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20161220_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='recorrido',
            field=models.ManyToManyField(blank=True, to='principal.recorrido'),
        ),
    ]
