# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20161220_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='horario_inicio',
            field=models.TimeField(null=True),
        ),
    ]
