# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20161220_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paradero',
            options={'ordering': ['nombre']},
        ),
    ]
